### ISSUE TITLE
Project Timeline

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#5]
A thread more specific for the task of creating our project timeline. 

We can discuss on how we want to go about it, using gantt charts or others.

**Comment by nivlekp** [comment]
Just to start with, I think gantt chart
-   is a nice way to visualise the project timeline;
-   would be useful in our reports.
However, if we were to draw gantt chart with a separate software, it would be tedious to keep the chart up to date.

The inbuilt function "Milestone" seems to be a pretty good way to give deadline to our tasks, and since it is part of Github, it would be able to reference "issues" and "projects".

[Here](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) is a pretty good link to the functionality of milestones. Feel free to have a look here before I have time later today or tomorrow to get back into looking further into this.

Also just a side note, if we were to use milestones within github, maybe we can write a script using Github's API to automatically draw a Gantt chart.

**Comment by nivlekp** [comment]
From what I can find, milestone has
-   due date
-   completion percentage
-   reference to issues and pull requests

Milestone can contain parts of different projects, and a project can span over multiple milestone.

The concept of milestone and project seems pretty intertwined to me. The inbuilt milestone seems to be a pretty good tool, but I am not sure how well it will function before we start using it. However since we are just a small team, I doubt if we would need sophisticated scheduling tools. If this does not work for us, I guess we can always fall back to using spreadsheets as Jonathan suggested.

I will just try to create a milestone for our task of deciding the project goal, and will see how well it works for us.

**Comment by relientm96** [comment]
I was looking at a few tools online available for Gannt chart generation from milestones and was planning to test it out but yeah I agree that if it is too difficult or tedious, we can just use spreadsheets. 

We can try setting milestones for now for the current issues that we have.

**Comment by relientm96** [comment]
Hey, I think for this thread, I think @nivlekp has setup a separate thread on github api gantt chart generation. We will move our further discussions there.
